In [25]:
import pandas as pd 

attr = pd.read_csv('AIS_data/precipitation-0.txt', delimiter='\t', names =["x-axis", "y-axis", "precipitation"])

air_temp = pd.read_csv('AIS_data/air_temp-0.txt', delimiter='\t', names = ["x-axis", "y-axis", "air_temp"])
extracted_col = air_temp["air_temp"]
attr = attr.join(extracted_col)

ocean_temp = pd.read_csv('AIS_data/theta_ocean-0.txt', delimiter='\t', names = ["x-axis", "y-axis", "ocean_temp"])
extracted_col = ocean_temp["ocean_temp"]
attr = attr.join(extracted_col)

ocean_salinity = pd.read_csv('AIS_data/salinity_ocean-0.txt', delimiter='\t', names = ["x-axis", "y-axis", "ocean_salinity"])
extracted_col = ocean_salinity["ocean_salinity"]
attr = attr.join(extracted_col)



ice_thickness = pd.read_csv('AIS_data/thk-0.txt', delimiter='\t', names = ["x-axis", "y-axis", "ice_thickness"])
extracted_col = ice_thickness["ice_thickness"]
ice_thickness = attr.join(extracted_col)
ice_thickness.to_csv('ice_thickness.csv', index=False)


ice_velocity = pd.read_csv('AIS_data/velsurf_mag-0.txt', delimiter='\t', names = ["x-axis", "y-axis", "ice_velocity"])
extracted_col = ice_velocity["ice_velocity"]
ice_velocity = attr.join(extracted_col)
ice_velocity.to_csv('ice_velocity.csv', index=False)

ice_mask = pd.read_csv('AIS_data/mask-0.txt', delimiter='\t', names = ["x-axis", "y-axis", "ice_mask"])
extracted_col = ice_mask["ice_mask"]
ice_mask = attr.join(extracted_col)
ice_mask.to_csv('ice_mask.csv', index=False)

,x-axis,y-axis,precipitation,air_temp,ocean_temp,ocean_salinity,ice_mask
0,-3040000,3040000,699.935242,292.724518,NaN,NaN,4.0
1,-2918400,3040000,678.224731,274.174042,NaN,NaN,4.0
2,-2796800,3040000,692.288513,273.751648,NaN,NaN,4.0
3,-2675200,3040000,700.634521,273.204681,NaN,NaN,4.0
4,-2553600,3040000,688.695557,272.617889,NaN,NaN,4.0
5,-2432000,3040000,672.626648,272.000732,NaN,NaN,4.0
6,-2310400,3040000,658.700745,271.372833,NaN,NaN,4.0
7,-2188800,3040000,632.239685,270.769318,NaN,NaN,4.0
8,-2067200,3040000,597.476501,270.114716,NaN,NaN,4.0
9,-1945600,3040000,577.078613,269.394012,NaN,NaN,4.0